In [20]:
from math import *
import numpy as np
import scipy.linalg as LA
import scipy.optimize as opt

def my_fixed_point(myfunc,xO,tol,maxIters,debug):
    """
    This program solves a system of nonlinear equations
    using the fixed point method within a specified
    tolerance.
    userFunc1 = lambda x: array([(x[0]**2 + 2.0)/3.0])
    >>> my_fixed_point(userFunc1,[0.],0.01,100,0)
    (array([0.98718895]), 8, 'Fixed point method converged.')
    >>> my_fixed_point([0.],0.01,100,1)
    iter = 1 x = [0.66666667]
    iter = 2 x = [0.81481481]
    iter = 3 x = [0.88797439]
    iter = 4 x = [0.92949951]
    iter = 5 x = [0.95465645]
    iter = 6 x = [0.97045631]
    iter = 7 x = [0.98059515]
    Fixed point method converged.
    (array([0.98718895]), 8, 'Fixed point method converged.')
    Written By
    Santiago El Awad (Computational Mechanics Course)
    """
    iIters, status = 0, "Not converged." #initializing the iterations and convergence message
    
    while True:
        if debug:
            print("iIter =", iIter, "x =", xO)
        
        if (iIters > maxIters):
            status = status + "Exceeded maxIters."
            break
            
        iIters = iIters + 1
        x = myfunc(xO)
        
        if LA.norm(x-xO) < tol:
            status = "Fixed point method converged."
            break
        else:
            xO = x
            print("iter =", iIters, "x =", xO)
            
    return (x,iIters,status)

In [21]:
userFunc1 = lambda x: np.array([(x[0]**2 + 2.0)/3.0])
my_fixed_point(userFunc1,[0.],0.01,100,0)

iter = 1 x = [0.66666667]
iter = 2 x = [0.81481481]
iter = 3 x = [0.88797439]
iter = 4 x = [0.92949951]
iter = 5 x = [0.95465645]
iter = 6 x = [0.97045631]
iter = 7 x = [0.98059515]


(array([0.98718895]), 8, 'Fixed point method converged.')